Make openshift-ci green 😇
- Update Makefile
- Add required files (for openshift-ci to work)
- Update e2e to not do secrets management

Signed-off-by: Vincent Demeester <vdemeest@redhat.com>

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -7,7 +7,7 @@ on:
       - "*"
     branches:
       - main
-  pull_request:
+  pull_request_target:
     branches:
       - main
 
@@ -24,19 +24,35 @@ jobs:
         run: make test-integration
 
   test-e2e:
+    strategy:
+      fail-fast: false # Keep running if one leg fails.
+      matrix:
+        pipeline-version:
+        - v0.44.5
+        - v0.47.5
+        - v0.50.5
+        - v0.53.2
+        - latest
     runs-on: ubuntu-latest
     needs:
       - test-integration
     steps:
-      - uses: actions/checkout@v3
+      - uses: actions/checkout@v4
         with:
           submodules: true
+
+      - name: Login to Docker Hub
+        uses: docker/login-action@v3
+        with:
+          registry: registry.redhat.io
+          username: ${{ secrets.REGISTRY_REDHAT_USERNAME }}
+          password: ${{ secrets.REGISTRY_REDHAT_TOKEN }}
 
       - uses: azure/setup-helm@v3
 
       # instantiate a KinD (Kubernetes in Docker) cluster, installs `kubectl` and configures the
       # `kubeconfig` to reach the local cluster
-      - uses: helm/kind-action@v1.5.0
+      - uses: helm/kind-action@v1.8.0
         with:
           cluster_name: kind
           wait: 120s
@@ -45,9 +61,16 @@ jobs:
       # settings to reach it during testing
       - uses: openshift-pipelines/setup-tektoncd@v1
         with:
-          pipeline_version: v0.41.0
-          cli_version: v0.29.1
+          pipeline_version: ${{ matrix.pipeline-version }}
 
       # running end-to-end test target
       - name: test-e2e
-        run: make test-e2e
+        run: |
+          set -Eeuo pipefail
+          kubectl delete secret regcred || true
+          kubectl create secret generic regcred \
+            --from-file=.dockerconfigjson=$HOME/.docker/config.json \
+          --type=kubernetes.io/dockerconfigjson
+          kubectl patch serviceaccount default -p '{"imagePullSecrets": [{"name": "regcred"}]}'
+          make test-e2e
+
